### ISSUE TITLE
Nested array of subdocuments

### ISSUE THREAD

**Issue by walame** [davellanedam/node-express-mongodb-jwt-rest-api-skeleton#100]
Hello,

If I have an array of nested documents in my model, how would you go about implementing the controller and its validation? And how would you pass the data to Postman?

Here is what my model looks like: 

```
const LeadSchema = new mongoose.Schema(
  {
    name: {
      type: String,
      required: true
    },
.
.
.
contacts: [
      {
        firstName: {
          type: String,
        },
        lastName: {
          type: String,
        },
        title: {
          type: String,
        }
        }
      }
    ]
.
.
.
```

Thank you very much!

**Comment by davellanedam** [comment]
Hello, this might help you:

https://mongoosejs.com/docs/subdocs.html

https://stackoverflow.com/questions/15208711/mongoose-subdocuments-vs-nested-schema

And controller and validation should be normal.
