### ISSUE TITLE
Emails with points

### ISSUE THREAD

**Issue by eliecer2000** [davellanedam/node-express-mongodb-jwt-rest-api-skeleton#11]
Hello Daniel, I've tried your code seems great, but I realized a small error, when the electronic mail that registers the user has points does not place them. Example: 

`elcorreo.deprueba@gmail.com `

in records records 

`elcorreodeprueba@gmail.com `

completely removes any point that has the address.

**Comment by davellanedam** [comment]
Hello Ecliecer, sorry about that I removed normalizeEmail() function from validator.js. It was removing dots from email addresses. Added new function in utils.js to convert an email in request to lowercase. Fixed on v.4.0.8
