### ISSUE TITLE
Error in the comparison of the password in the case of being different

### ISSUE THREAD

**Issue by eliecer2000** [davellanedam/node-express-mongodb-jwt-rest-api-skeleton#12]
hi dave! how much the route / login is executed, in the case that the password is different, an error is stored in the update of the loginAttempts field of the user model. 

`Cast to Number failed for value "NaN" at path loginAttempts `

checking the model is selected: false and should be true.

```
    loginAttempts: {
      type: Number,
      default: 0,
      select: false
    },

```

```
    loginAttempts: {
      type: Number,
      default: 0,
      select: true
    },

```

**Comment by davellanedam** [comment]
I see no error at all, just tested it, maybe you changed the behavior of the login? It´s false on purpose, so that value doesn't come always you query the user model, check function findUser() at auth.js, there you will see I explicitly call it, with the password and blockExpires as well (line 179)
