### ISSUE TITLE
Flexible Route Authorization

### ISSUE THREAD

**Issue by olafwrieden** [davellanedam/node-express-mongodb-jwt-rest-api-skeleton#124]
**Is your feature request related to a problem? Please describe.**
Sometimes I find myself calling an endpoint to perform an action only to find out that I do not have the necessary permissions to perform the action. Here is the example:

* As a non-admin user, I would like to delete my own account. However, the `DELETE /users/:id` endpoint is restricted to the `admin` role.

**Describe the solution you'd like**
Because the role auth is handled in the route component, I would like to see some way for the API request to go ahead if the requested resource is regarding the user him/herself but not another user.
The example here may be that user 1 is an admin and therefore able to delete all users. User 2 may be a standard user and can delete the account if the returned resource is the user's own data but not someone else's (I hope that makes sense).

**Describe alternatives you've considered**
N/A

**Comment by davellanedam** [comment]
I would day if you want to delete your own account there should be a new endpoint as its logic would be different, it has to be sure that you are really you and only trying ti delete yourself. Also some kind of email confirmation would be nice.
