### ISSUE TITLE
refresh token implementation

### ISSUE THREAD

**Issue by NinthAutumn** [davellanedam/node-express-mongodb-jwt-rest-api-skeleton#13]
User has to relogin everytime the jwt token expires and that is a problem

so I believe implementing refresh token would be great

**Comment by davellanedam** [comment]
Hello Ninth, I just released a new version 6.0.0 https://github.com/davellanedam/node-express-mongodb-jwt-rest-api-skeleton/pull/14 with that feature, also changed a constant in .env so keep that in mind
