### ISSUE TITLE
why Auto add OPTIONS request to Server

### ISSUE THREAD

**Issue by stone89son** [davellanedam/node-express-mongodb-jwt-rest-api-skeleton#143]
**Describe the bug**
auto add OPTIONS request to Server

**To Reproduce**

1. Press F12 on FireFox -> Network->XHR
2. Go to Login by Admin
3. Click on Delete,Add,Update

**Screenshots**
.
![Screenshot from 2019-10-09 20-36-28](https://user-images.githubusercontent.com/6795515/66478416-523a5900-ead5-11e9-8a12-c06b7ea5c4ac.png)

 - OS: [Ubuntu]

**Comment by davellanedam** [comment]
OPTIONS requests are what we call pre-flight requests in Cross-origin resource sharing (CORS).

They are necessary when you're making requests across different origins in specific situations.

This pre-flight request is made by some browsers as a safety measure to ensure that the request being done is trusted by the server. Meaning the server understands that the method, origin and headers being sent on the request are safe to act upon.

Your server should not ignore but handle these requests whenever you're attempting to do cross origin requests.

A good resource can be found here http://enable-cors.org/
