### ISSUE TITLE
Duplicate user creation flow

### ISSUE THREAD

**Issue by ccpandhare** [davellanedam/node-express-mongodb-jwt-rest-api-skeleton#192]
There are two API endpoints for user creation:
- `POST /register` (doesn't require auth) [`auth.register`]
- `POST /users` (requires Admin level auth) [`user.createItem`]

The only difference is that `POST /users` allows predefinition of the 'role' field.
From what I could understand, this solves a very niche problem of giving Admin higher authority to create accounts (by allowing one additional field). Is this all there is to this, or am I missing some important usage here? Was this the intended behaviour and difference between the two?

**Comment by davellanedam** [comment]
You are right, it’s the intention to do that, so you guys at the end will choose the best path that fits your needs

**Comment by ccpandhare** [comment]
I see! Thanks for the clarification!
