### ISSUE TITLE
Add Logout Feature to User with Code

### ISSUE THREAD

**Issue by RameshNagoor** [davellanedam/node-express-mongodb-jwt-rest-api-skeleton#194]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by davellanedam** [comment]
Hi, logout is being handled in front end (project here https://github.com/davellanedam/vue-skeleton-mvp) There's no need to create logout here as when user logs in a token is created with an specific validity if you want to.
