### ISSUE TITLE
How to enable certain endpoints to not be authorized(certain endpoints not require JWT

### ISSUE THREAD

**Issue by kyeljmd** [davellanedam/node-express-mongodb-jwt-rest-api-skeleton#197]
How to enable certain endpoints to not be authorized(certain endpoints not require JWT

**Comment by davellanedam** [comment]
Just don't use `AuthController.roleAuthorization(['user', 'admin'])` in the router for the specific endpoint.

**Comment by davellanedam** [comment]
Closing this. No response means probably it’s solved
