### ISSUE TITLE
app crashed - waiting for file changes before starting

### ISSUE THREAD

**Issue by AmitPrajapati1902** [davellanedam/node-express-mongodb-jwt-rest-api-skeleton#2]
> 
> [nodemon] 1.18.6
> [nodemon] to restart at any time, enter `rs`
> [nodemon] watching: *.*
> [nodemon] starting `node server.js`
> events.js:183
>       throw er; // Unhandled 'error' event
>       ^
> 
> Error: Redis connection to 127.0.0.1:6379 failed - connect ECONNREFUSED 127.0.0.1:6379
>     at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1191:14)
> [nodemon] app crashed - waiting for file changes before starting...
> 
> >

**Comment by davellanedam** [comment]
You must install redis server to enable cache, that’s the message, set host and port in the .env file also. Let me know how it goes.
