### ISSUE TITLE
Correct syntax for Redis cache

### ISSUE THREAD

**Issue by Amine27** [davellanedam/node-express-mongodb-jwt-rest-api-skeleton#200]
Hello,
Thank you for this wonderful API skeleton, it helps a lot.

Trying to enable Redis cache, I got this error:

`Error: Redis connection to 127.0.0.1:6379 failed - connect ECONNREFUSED 127.0.0.1:6379`

Changing connection syntax to this:

```
    engine: require('expeditious-engine-redis')({
      redis: {
        host: process.env.REDIS_HOST,
        port: process.env.REDIS_PORT
      }
    })
```

fixed the error for me.
Thank you.

**Comment by davellanedam** [comment]
Hey thank you!, Well, I think you forgot to enable redis from env variables. You should do this in your .env file

`USE_REDIS=true`

Check the code:
```
// Redis cache enabled by env variable
if (process.env.USE_REDIS === 'true') {
  const getExpeditiousCache = require('express-expeditious')
  const cache = getExpeditiousCache({
    namespace: 'expresscache',
    defaultTtl: '1 minute',
    engine: require('expeditious-engine-redis')({
      host: process.env.REDIS_HOST,
      port: process.env.REDIS_PORT
    })
  })
  app.use(cache)
}
```

**Comment by Amine27** [comment]
Of course I did, please take a look at this:
https://github.com/evanshortiss/expeditious-engine-redis/issues/1
Or try it yourself :)

**Comment by davellanedam** [comment]
Hey there again, I just tested it with current setup and it works perfect. I changed to your suggestion anyways as that seems to be the official way. Thank you! Fixed version it's 8.1.3

**Comment by Amine27** [comment]
I forget to mention that I am using a Docker setup, perhaps it has something to do with this (network change).
Thank you.

**Comment by davellanedam** [comment]
Yeah, probably it does, I added the change anyways, so hopefully other people with your setup won't have any issues, thank you again for reporting this!
