### ISSUE TITLE
MognoAltas issue ?

### ISSUE THREAD

**Issue by leifermendez** [davellanedam/node-express-mongodb-jwt-rest-api-skeleton#213]
Doubt. Since a few months ago I am a user of your repository and I have several projects in production using, in 2 of these projects I have had the same problem. Which I don't know if it's something in the code or more in the server configuration. As I mentioned it is just a query to know if the same thing has happened to someone else. The problem is that I have a connection with MongoAtlas and suddenly the connection number goes up to the limit. Attached are screenshots of two projects

![image](https://user-images.githubusercontent.com/15802366/97106221-8cff3700-16c0-11eb-9273-f36460da439f.png)

![image](https://user-images.githubusercontent.com/15802366/97106247-b029e680-16c0-11eb-8243-5441f3521b55.png)

I understand that it can be assumed of an increase of users using the application, but the truth is that it is not the case the number of users is relatively equal always

Thank you !

**Comment by davellanedam** [comment]
Hello! So you say you are using the api in several projects, but 2 of those several are having issues? That sounds to me something is wrong in your code? Otherwise all of your projects should fail, right? Also I released a new version some weeks ago, you may try that route having functions in their own file and maybe use Jest for unit testing and test deeper? Thanks for the feedback!

**Comment by leifermendez** [comment]
Yeah it's possible. Can you recommend me a tool for tracking issue inside server.

**Comment by davellanedam** [comment]
Mongo Atlas itself should provide you more details. Maybe you can also use a third party log keeper and analyze those logs. Let me know how it goes.

**Comment by leifermendez** [comment]
I know but not database I referre on general For example I have a morgan for log http errors connect with slack webhook. But it's work only when http responsed. I want when code crash in general.

**Comment by davellanedam** [comment]
Yeah, please check latest version I released. In the middleware you will see the handleError function, there you can set something additional, like datadog logger or something more advanced. I don’t know what is your current implementation. Take a look at new version and maybe you can implement those changes on your side. Maybe also setting a log when a connection is created. You will have to add log points in key places.

**Comment by leifermendez** [comment]
Ok. Thank you! Have a nice day
