### ISSUE TITLE
Mailgun fails for hosting in EU regions

### ISSUE THREAD

**Issue by dwf981** [davellanedam/node-express-mongodb-jwt-rest-api-skeleton#222]
Mailgun will fail when the app is hosted on a european server (no explicit error) due to Mailgun configuration.

To reproduce:
- install/run the app from an EU location/server
- try to trigger email sending (ie: register)
- vague error in console

PS: my solution for hosting the app in the EU region:
Edit **sendEmail.js** like this:
```
  const auth = {
    auth: {
      // eslint-disable-next-line camelcase
      api_key: process.env.EMAIL_SMTP_API_MAILGUN,
      domain: process.env.EMAIL_SMTP_DOMAIN_MAILGUN
    },
    host: 'api.eu.mailgun.net'
  }
```
Related issue:
https://github.com/mailgun/mailgun-php/issues/471

**Comment by davellanedam** [comment]
Thanks! Fixed in v 9.0.3
