### ISSUE TITLE
Best way to check logged in user from another service?

### ISSUE THREAD

**Issue by squidis** [davellanedam/node-express-mongodb-jwt-rest-api-skeleton#226]
Thanks for maintaining what looks like a great authentication api. I'm trying to setup a user service that my other api's can pass a JWT to to check if a user is authenticated. As this package uses a blocklist am I right in thinking that I need to call this central service as opposed to decrypting the JWT to get the user ID? 

Would it be a case of adding a new route like the refresh token route, something like this?
`router.get(
  '/whoami',
  requireAuth,
  roleAuthorization(['user', 'admin']),
  trimRequest.all
)`

**Comment by davellanedam** [comment]
Hey @squidis! Thank you, yeah, you can do that as well.
