### ISSUE TITLE
Email Links Not Working

### ISSUE THREAD

**Issue by olafwrieden** [davellanedam/node-express-mongodb-jwt-rest-api-skeleton#28]
@davellanedam 
I am registering a new user and an email has been sent, however, the verification link emailed is in the format `[FRONTEND_URL]/verify/[VERIFICATION]` while the verify method called by the endpoint upon clicking the link is looking for an `id` in the _POST_ request.
This yields the error: `{"errors":{"msg":"URL_NOT_FOUND"}}`

Unit tests do not reveal this issue as the generated verification code is returned in _development_ mode but not in _production_.

I believe the same applies to the _Reset Password_ email. Please take a look.

**Comment by davellanedam** [comment]
Can you please elaborate? It’s like that because you are not supposed to open a link from your email and go directly to the API, a frontend should handle that click, and then take the verification ID and send it as a POST to the API endpoint.

**Comment by olafwrieden** [comment]
I see that makes perfect sense now. It wasn't apparent initially as I thought it reached out to the API directly, thank you for the clarification.

**Comment by davellanedam** [comment]
I’m here to help!
