### ISSUE TITLE
Password not encrypted when updating in profile

### ISSUE THREAD

**Issue by ramoncardena** [davellanedam/node-express-mongodb-jwt-rest-api-skeleton#3]
**Describe the bug**
When I try to change password, the patch method on profile works, but saves the password without hashing it.

**To Reproduce**
Call http://localhost:5000/profile with
{
 "password": "newpassword"
}
as body.

The result is the profile object and when you check the Mongo db, you see the password field un-hashed.

**Comment by davellanedam** [comment]
I am really really sorry about that, its already fixed on v.1.2.3.

**Comment by ramoncardena** [comment]
Thanks Dave. Great work on this api!

**Comment by davellanedam** [comment]
You are welcome Ramon! Let me know if you find anything else, or maybe a new feature. Cheers!
