### ISSUE TITLE
Validation results are doubled

### ISSUE THREAD

**Issue by neural9** [davellanedam/node-express-mongodb-jwt-rest-api-skeleton#33]
Validation results are doubled when calling API with zero parameters.

On a post to /cities with nothing added other than bearer token for example, the following occurs:

```
{
    "errors": {
        "msg": [
            {
                "location": "body",
                "param": "name",
                "msg": "MISSING"
            },
            {
                "location": "body",
                "param": "name",
                "msg": "IS_EMPTY"
            }
        ]
    }
}
```

**Comment by davellanedam** [comment]
Yeah, it’s how validator dependency plugin works, it returns an array with all validation errors, the one you got is that you didn’t send the param ‘name’ and also that it’s empty.

**Comment by neural9** [comment]
Ah understood - thank you.

**Comment by davellanedam** [comment]
No worries, anytime bud,  also says body because you can send params in body or maybe query, so that’s useful also.
