### ISSUE TITLE
Add role validation to USer creator

### ISSUE THREAD

**Issue by neural9** [davellanedam/node-express-mongodb-jwt-rest-api-skeleton#35]
When creating a user, if you don't use an expected role from the user model enum then it crashes out with:

(node:8996) [DEP0106] DeprecationWarning: crypto.createDecipher is deprecated.
warning.js:27
TypeError: Cannot read property 'toObject' of undefined
    at /Users/rob/Documents/Projects/oped/oped/app/controllers/users.js:42:43
    at /Users/rob/Documents/Projects/oped/oped/node_modules/mongoose/lib/model.js:4732:16

To solve, add:

    .isIn(['admin', 'user','superuser'])
    .withMessage('USER_NOT_IN_KNOWN_ROLE'),

to the user validation in users.validate.js.

Thanks,

Rob

**Comment by davellanedam** [comment]
Hi Rob, thank you, just fixed in [v.6.1.13](https://github.com/davellanedam/node-express-mongodb-jwt-rest-api-skeleton/releases/tag/v6.1.13). Also made a [test for it](https://github.com/davellanedam/node-express-mongodb-jwt-rest-api-skeleton/commit/72023a219d1de09f646b0ccf6be11f975aa79abd).
