### ISSUE TITLE
Util for accessing userId from token 

### ISSUE THREAD

**Issue by neural9** [davellanedam/node-express-mongodb-jwt-rest-api-skeleton#37]
When business logic requires a userId to do something such as create a new City, the userId should be pulled from the encrypted JWT and therefore the engineer needs easy access to that ID.

**Comment by neural9** [comment]
It is there already 

`req.user._id

This strips it:

`req = matchedData(req)

**Comment by davellanedam** [comment]
Yeah, if you need it you can set it on the validation. The purpose of validation is to only get what you need: cleaned and validated. Any other param will be stripped out.

**Comment by lardissone** [comment]
@davellanedam I'm not sure how to access the logged in user object from the controller. 
Here's my example. I need to set the `owner` key with the logged in `_id`.

This is my controller:

```js
const createItem = async req => {
  return new Promise((resolve, reject) => {
    console.log(req.user._id)  // undefined
    const patient = new model({
      owner: req.user._id,  // <--- returns error because undefined
      firstName: req.firstName,
      lastName: req.lastName,
      ...
```
Not sure what should I do in the validation as you mention in the previous comment.

**Comment by davellanedam** [comment]
Please check profile controller, I get the id and check it, then it is assigned to a constant that can be used to send to other functions.

**Comment by lardissone** [comment]
Got it, thanks!
