### ISSUE TITLE
Filter on objectid

### ISSUE THREAD

**Issue by neural9** [davellanedam/node-express-mongodb-jwt-rest-api-skeleton#38]
I want to be able to search for all cities I created (for example).

If I add a 'userid' field to the cities model then I want to be able to

cities?filter=5aa1c2c35ef7a4e97b5e995b&fields=userid&limit=2&page=1

That way, I can utilise the pagination pattern built into the API.

I can add in 
    query['userId'] = new ObjectId(req.user.id)
to the controller but this feels like a workaround to the pattern.

**Comment by davellanedam** [comment]
Then you should have a cities array in users model according your example

**Comment by neural9** [comment]
Yes, that would be ideal in principle but in a large application would that pattern work? 

If you take youtube as an example, then the users model would hold: all videos the user uploaded, all likes, all subscriptions, all messages etc. It would even hold all 'clicks' if you were doing analytics etc. That's a big user model.

I think practically, you'd need to break it up wouldn't you?

**Comment by davellanedam** [comment]
Ok, I see, then Aggregate in MongoDB can save your day, but you’ll need to modify the built-in search for that.

**Comment by neural9** [comment]
I'll see how much success I have with it and post the code if it's generically useful

**Comment by davellanedam** [comment]
Sure, PR are always welcome!
