### ISSUE TITLE
Not standardized response on error

### ISSUE THREAD

**Issue by ramoncardena** [davellanedam/node-express-mongodb-jwt-rest-api-skeleton#4]
When fetching data from the backend you got a response object. When there are errors the object is called 'errors' and if the errors are from validation, you get an array with the location, param, value and msg.

The problem is with POST /register, when you send an incorrect email like "asdasd@asdas" you don't get the validation error object, just a plain error object:

> Object
> errors: msg: "User validation failed: email: EMAIL_IS_NOT_VALID"
> __proto__: Objec
> t__proto__: Object

Instead of:

> Object
> errors:
> msg: Array(1)
> 0: {location: "body", param: "email", value: "asdasd@asdas", msg: "EMAIL_IS_NOT_VALID"}
> length: 1
> __proto__: Array(0)
> __proto__: Object
> __proto__: Object

On the other hand, if you send an invalid email in POST /login you get the right validation error.

It's possible to standardize all errors to just get WHATEVER_WHATEVER (like IS_EMPTY)?

**Comment by davellanedam** [comment]
Hi Ramon! Thanks, I just fixed in release v.1.2.4. Again if you find anything else or have any ideas to improve, just let me know. Cheers!

**Comment by ramoncardena** [comment]
Thanks Dave! Works great with my frontend now!
I've done a couple of small changes to fit my needs, like I change some of the error returns from sentences to codes like EMAIL_IS_NOT_VALID so I can add the codes to my i18n file and write the error messages in multiple languages, and I have also added the role to the return when fetching profile, so I can check role at the moment without storing it in local storage or cookies. I can open open the issues for them if you want to add them.

**Comment by davellanedam** [comment]
Hi Ramon, well using uppercase and dashes for responses allows you to set a constant and then your message for i18n, I think it´s more readable that way so people understands easier, if changing to numbers works for you it´s great! But for learning purposes I think it´s better as it is now. Also the role is returning now when getting/patching profile in v.1.2.6.

**Comment by ramoncardena** [comment]
Hi Daniel! sorry I haven't explained myself well! I meant that I changed some responses to uppercase and dashes to unify all the responses  as uppercase and dashes. When I arrive to the office later I'll send you the responses I changed.
