### ISSUE TITLE
No length verification on password when updating profile

### ISSUE THREAD

**Issue by ramoncardena** [davellanedam/node-express-mongodb-jwt-rest-api-skeleton#5]
When updating profile with PATCH /profile if you change password, there's no check on length. So if the user change password for a 3 chars word, no error is returned and then when trying to login, the verification on login works and it doesn't allows you to enter a 3 chars word as password.

**Comment by davellanedam** [comment]
Hi Ramon, thank you, fixed in v.1.2.6.

**Comment by ramoncardena** [comment]
Thanks Daniel!
