### ISSUE TITLE
A way to simplify internationalization?

### ISSUE THREAD

**Issue by kleydon** [davellanedam/node-express-mongodb-jwt-rest-api-skeleton#89]
Very inspiring project. Thanks for posting it!

I had an idea, which may make internationalization more concise:

Right now, every place where there is internationalized text, you must include $t() around it - but this may not be necessary.

Given that Vue is a framework that automatically re-renders in response to changes in state, what if you used an approach like in this blog posting?

https://ourcodeworld.com/articles/read/395/getting-started-with-internationalization-i18n-in-react

The idea is to set the language by changing the required file path for the internationalized strings, and have a state variable depend on this change, such that components automatically update.

Its just an idea; see what you think.

Thanks again for posting this repo!

**Comment by davellanedam** [comment]
Thank you kleydon! I love it’s helpful for you. I think you commented in the wrong repo, this is the API! :) I would love to see some example from you, I actually used the most popular i18n plugin for Vue and also external JSON files to store languages. In their documentation they suggest using the $t format, but would love to see a simpler approach. Please create a pull request so we can both try to improve the project. Thank you again!

**Comment by kleydon** [comment]
I just tried, and the Vue i18n plugin doesn't have the setTexts() method that i18n-react has - so this approach isn't going to work, unfortunately. At least not easily...
