### ISSUE TITLE
Migrating passwords from another system

### ISSUE THREAD

**Issue by walame** [davellanedam/node-express-mongodb-jwt-rest-api-skeleton#97]
Firstly, thank you for this awesome project!!

I am trying to find a way to migrate users & passwords from a previous fullstack system that is built using `node-express-mongoose-bcrypt`. Your structure is far superior, and it would save me A LOT of time to mgirate.

Steps I followed:

1) Change SALT_ROUNDS to 10, to match the old system
2) Registered for a new user with this project
2) Copied the password hash from the OLD mongo User collection
3) Pasted it (using a mongo visualization tool) to this project's User collection in the password field.

When I try /login via Postman, the system crashes with this error:

```
TypeError: this.buildErrObject is not a function
    at user.comparePassword (/Users/w/Github/wfs/app/middleware/auth.js:16:23)
    at bcrypt.compare (/Users/w/Github/wfs/app/models/user.js:115:11)
    at /Users/w/Github/wfs/node_modules/bcrypt-nodejs/bCrypt.js:689:3
    at process._tickCallback (internal/process/next_tick.js:61:11)
```

Can you please weigh in on this error? Otherwise, can you please suggest the best way to migrate passwords?

Many thanks!
W

**Comment by davellanedam** [comment]
Hello Walame, well I'm using here a different bcrypt library, I don't know if that can be the problem. Also check if you are using the same old secret to encrypt in your old implementation (here, jwt secret defined in the .env). And finally you should use a try/catch to get more info about it. Without explicit code from you its hard to say. I hope this helps.
